### ISSUE TITLE
Relicense to LGPLv2.1+

### ISSUE THREAD

**Issue by pwithnall** [pwithnall/dbus-deviation#7]
Licensing under GPL/AFL was a mistake, and means that combining dbus-deviation with LGPL code (or copying LGPL code into it) is not possible or has non-obvious consequences.

I would like to relicense dbus-deviation to LGPLv2.1+.

From the output of `$ git log --format=format:%an | sort -u`, the current contributors are:
 * Kaloyan Tenchov
 * Mathieu Duponchelle
 * Philip Withnall

@zayfod, @MathieuDuponchelle, are you OK with relicensing, and if so can you please confirm that here?

**Comment by MathieuDuponchelle** [comment]
Sure, go ahead

**Comment by pwithnall** [comment]
@zayfod?

**Comment by zayfod** [comment]
Sure. I personally like LGPL better. Thanks for asking.

**Comment by pwithnall** [comment]
Done, thanks all. I’ll release 0.5.0 soon (probably after @zayfod’s work has landed).
